# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import message_pb2 as message__pb2


class ExecutorStub(object):
    """The execution service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ApplyChange = channel.unary_unary(
                '/Executor/ApplyChange',
                request_serializer=message__pb2.ChangeRequest.SerializeToString,
                response_deserializer=message__pb2.ChangeReply.FromString,
                )


class ExecutorServicer(object):
    """The execution service definition.
    """

    def ApplyChange(self, request, context):
        """Sends a request to apply a change to the Raspberry Pi and a response to the Flask API.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ExecutorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ApplyChange': grpc.unary_unary_rpc_method_handler(
                    servicer.ApplyChange,
                    request_deserializer=message__pb2.ChangeRequest.FromString,
                    response_serializer=message__pb2.ChangeReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Executor', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Executor(object):
    """The execution service definition.
    """

    @staticmethod
    def ApplyChange(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Executor/ApplyChange',
            message__pb2.ChangeRequest.SerializeToString,
            message__pb2.ChangeReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
